import type { Metadata } from "next";
import "./globals.css";
import {Inter} from "next/font/google"


const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "700", "900"],
  style: ["normal", "italic"],
})

export const metadata: Metadata = {
  title: "Lost It? Find It!,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <main>
        {children}
      </main>
      </body>
    </html>
  );
}
